AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  imagesetconverterlambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: ''
      MemorySize: 256
      Timeout: 20
      Role: >-
        arn:aws:iam::286751717145:role/avi-image-labels-converter-lambda-vpc-role
      Events:
        SQS1:
          Type: SQS
          Properties:
            Queue:
              'Fn::GetAtt':
                - SQSQueue1
                - Arn
            BatchSize: 1
      VpcConfig:
        SecurityGroupIds:
          - sg-5e4b7536
        SubnetIds:
          - subnet-a876b0c0
          - subnet-c78bb1bc
          - subnet-7aaed537
      Layers:
        - 'arn:aws:lambda:us-east-2:286751717145:layer:opencv-numpy-pymysql:1'
  SQSQueue1:
    Type: 'AWS::SQS::Queue'
    Properties: {}
